
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - shop_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shop_db:5432/Shop_Project_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  shop_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Shop_Project_DB
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5433:5432"

volumes:
  pg_data:




